services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $disable: '%sac_evt_reg_reminder.disable%'
            $allowWebScope: '%sac_evt_reg_reminder.allow_web_scope%'
            $sid: '%sac_evt_reg_reminder.sid%'
            $maxNotificationsPerRequest: '%sac_evt_reg_reminder.max_notifications_per_request%'
            $defaultLocale: '%sac_evt_reg_reminder.default_locale%'

    Markocupic\SacEventRegistrationReminder\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Data/Data.php}


